name: "Azos Actions - Version File"
decription: "Github action to create a simple version file based in git release tags and last commit hash"
author: "Eduardo Medeiros Pereira"

inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true

outputs:
  version:
    description: "Version file with version:hash. Version from release tag and hash from last commit"

runs:
  using: "node12"
  main: "dist/index.js"
